### ISSUE TITLE
How did you find the login URL `/huc/user/foo/login.do`

### ISSUE THREAD

**Issue by muyinliu** [ripples-alive/SMS#1]
How did you find the login URL `/huc/user/foo/login.do`?

**Comment by ripples-alive** [comment]
In my mind, I just easily found it on web fetion.
And I run this program again and found that the program seems doesn't work now.
Maybe this login url has been forbidden?

**Comment by muyinliu** [comment]
That's odd...I just test it in the morning and it work but it doesn't work now!

**Comment by ripples-alive** [comment]
Em... It seems really strange... Maybe you can try again a few days later?
